/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(require('./crossjumprotation.gltf'))
  const { actions } = useAnimations(animations, group)
  useEffect( () => { console.log(actions); actions.Movement.play() } )
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          geometry={nodes.LP_Девушка.geometry}
          material={materials['Цвет тела.012']}
          skeleton={nodes.LP_Девушка.skeleton}
        />
        <skinnedMesh
          geometry={nodes.LP_Девушка001.geometry}
          material={nodes.LP_Девушка001.material}
          skeleton={nodes.LP_Девушка001.skeleton}
        />
        <skinnedMesh
          geometry={nodes.LP_Девушка002.geometry}
          material={nodes.LP_Девушка002.material}
          skeleton={nodes.LP_Девушка002.skeleton}
        />
        <skinnedMesh geometry={nodes.Глаза.geometry} material={materials['Глаз.012']} skeleton={nodes.Глаза.skeleton} />
        <skinnedMesh
          geometry={nodes.Ресницы.geometry}
          material={materials['Материал.012']}
          skeleton={nodes.Ресницы.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload(require('./crossjumprotation.gltf'))
