/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(require('./pistol.gltf'))
  const { actions } = useAnimations(animations, group)
  useEffect( () => { console.log(actions); actions.Movement.play() } )
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          geometry={nodes.LP_Девушка009.geometry}
          material={materials['Цвет тела.007']}
          skeleton={nodes.LP_Девушка009.skeleton}
        />
        <skinnedMesh
          geometry={nodes.LP_Девушка010.geometry}
          material={nodes.LP_Девушка010.material}
          skeleton={nodes.LP_Девушка010.skeleton}
        />
        <skinnedMesh
          geometry={nodes.LP_Девушка011.geometry}
          material={nodes.LP_Девушка011.material}
          skeleton={nodes.LP_Девушка011.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Глаза003.geometry}
          material={materials['Глаз.007']}
          skeleton={nodes.Глаза003.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Ресницы003.geometry}
          material={materials['Материал.007']}
          skeleton={nodes.Ресницы003.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload(require('./pistol.gltf'))
